<?php
// This file generated by Propel 1.7.0 convert-conf target
// from XML runtime conf file C:\Development\fishbase\runtime-conf.xml
$conf = array (
  'datasources' => 
  array (
    'fbapp' => 
    array (
      'adapter' => 'mysql',
      'connection' => 
      array (
        'dsn' => 'mysql:host=localhost;dbname=fbapp',
        'user' => 'root',
        'password' => 'qwerty',
      ),
    ),
    'default' => 'fbapp',
  ),
  'generator_version' => '1.7.0',
);
$conf['classmap'] = include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'classmap-fbapp-conf.php');
return $conf;